// Epona sync; Faron Field has a horse on a fresh save; HORSE_HOLD <what> (on A) marks captures.

const { STAGES, COMMON_CVARS, tt, barrier, meetIn, connect, warp, waitStage } = require("../lib");

const RED = "e53935";
const colorCvars = (hex) => [tt("color", hex)];
// B's save calls its horse Lilly (the design's example: "Dad's Lilly").
const B_START = { ...STAGES.faronField, horseName: "Lilly" };
// Cards and tags are read from the screen: those checks hold the camera on the horse.
const CAM = { target: "remote", back: 450, up: 320 };
const onCamera = (steps, what, camera = CAM, sec = 4) => [
    { op: "horseCamera", ...camera, hold: true },
    { op: "wait", frames: 5 },
    ...steps,
    { op: "mark", msg: `HORSE_HOLD ${what}` },
    { op: "wait", sec },
    { op: "horseCamera", release: true },
];
const field = STAGES.faronField;

module.exports = [
    {
        name: "horse-solo",
        description: "one instance in Faron Field gets its Epona in front of it, rides her (forced, then the real mount), gallops a loop and gets off: the harness the horse scenarios build on",
        timeoutSec: 240,
        cvars: COMMON_CVARS,
        instances: [
            {
                name: "solo",
                start: field,
                steps: [
                    waitStage(field),
                    { op: "clearEnemies" },
                    { op: "spawnHorse" },
                    { op: "expectLocalHorse", present: true, ridden: false },
                    { op: "rideHorse", mode: "force" },
                    { op: "expectLocalHorse", ridden: true },
                    { op: "walk", frames: 150, circle: true },
                    { op: "wait", frames: 30 },
                    { op: "rideHorse", ride: false },
                    { op: "expectLocalHorse", ridden: false },
                    { op: "rideHorse", mode: "mount" },
                    { op: "expectLocalHorse", ridden: true },
                    { op: "walk", frames: 90, stickY: 1 },
                    { op: "wait", frames: 30 },
                    { op: "rideHorse", ride: false },
                    { op: "expectLocalHorse", ridden: false },
                    { op: "quit" },
                ],
            },
        ],
    },
    {
        name: "horse-remote",
        description: "B (red, its horse named Lilly) gets its Epona: A sees her with the card \"B's Lilly\" and a red-tinted mane; B mounts: A's puppet carries B's dummy in the saddle (root seated, not floating) with B's tag reading B / Lilly and no card, also while B gallops; B gets off; A cannot get the ride prompt on B's horse, and pressing A beside it rides nothing",
        timeoutSec: 420,
        cvars: COMMON_CVARS,
        instances: [
            {
                name: "A",
                start: field,
                steps: [
                    ...connect,
                    ...meetIn(field, "B"),
                    { op: "clearEnemies" },
                    { op: "waitSignal", name: "spawned", from: "B", timeoutSec: 60 },
                    { op: "expectRemoteHorse", ridden: false, tint: true, frames: 30 },
                    ...onCamera([{ op: "expectRemoteHorse", ridden: false, card: "B's Lilly", onScreen: true, frames: 5 }], "card"),
                    ...barrier("saw-horse", "B"),
                    { op: "waitSignal", name: "mounted", from: "B", timeoutSec: 60 },
                    ...onCamera([{ op: "expectRemoteHorse", ridden: true, card: false, tagLine2: "Lilly", onScreen: true, maxSeatDist: 60, frames: 5 }], "rider"),
                    ...barrier("saw-rider", "B"),
                    { op: "waitSignal", name: "galloping", from: "B", timeoutSec: 60 },
                    { op: "expectRemoteHorse", ridden: true, card: false, tagLine2: "Lilly", maxSeatDist: 60, frames: 90, timeoutSec: 30 },
                    { op: "checkDummies", maxDist: 400 },
                    ...barrier("saw-gallop", "B"),
                    { op: "waitSignal", name: "dismounted", from: "B", timeoutSec: 60 },
                    { op: "expectRemoteHorse", ridden: false, card: "B's Lilly", tagLine2: "", frames: 5, timeoutSec: 20 },
                    // Only our own horse can be ridden (A's own waits, far away, to be called).
                    { op: "setHorseHidden", hidden: true },
                    { op: "expectRidePrompt", target: "remote", frames: 60 },
                    { op: "walk", frames: 10, stickX: 0, stickY: 0, buttons: 0x100 },
                    { op: "expectNotRiding", frames: 60 },
                    ...barrier("tried-ride", "B"),
                    { op: "quit" },
                ],
            },
            {
                name: "B",
                start: B_START,
                cvars: colorCvars(RED),
                steps: [
                    ...connect,
                    ...meetIn(field, "A"),
                    { op: "clearEnemies" },
                    { op: "walk", frames: 40, stickY: 1 },
                    { op: "spawnHorse", dist: 300, side: 120 },
                    { op: "signal", name: "spawned" },
                    ...barrier("saw-horse", "A"),
                    { op: "rideHorse", mode: "mount" },
                    { op: "expectLocalHorse", ridden: true },
                    { op: "wait", frames: 30 },
                    { op: "signal", name: "mounted" },
                    ...barrier("saw-rider", "A"),
                    { op: "signal", name: "galloping" },
                    { op: "walk", frames: 240, circle: true },
                    { op: "expectLocalHorse", ridden: true },
                    ...barrier("saw-gallop", "A"),
                    { op: "rideHorse", ride: false },
                    { op: "expectLocalHorse", ridden: false },
                    { op: "signal", name: "dismounted" },
                    ...barrier("tried-ride", "A"),
                    // A's attempt left B's own horse with B, unridden.
                    { op: "expectLocalHorse", ridden: false },
                    { op: "quit" },
                ],
            },
        ],
    },
    {
        name: "horse-own-prompt",
        description: "both have their Epona side by side: A gets the ride prompt on its own horse but never on B's; A's own horse is untinted on A's screen next to B's tinted one",
        timeoutSec: 300,
        cvars: COMMON_CVARS,
        instances: [
            {
                name: "A",
                start: field,
                steps: [
                    ...connect,
                    ...meetIn(field, "B"),
                    { op: "clearEnemies" },
                    { op: "spawnHorse", dist: 300 },
                    { op: "waitSignal", name: "spawned", from: "B", timeoutSec: 60 },
                    { op: "expectRemoteHorse", ridden: false, tint: true, frames: 15 },
                    ...onCamera([], "manes", { target: "both", back: 550, up: 400 }),
                    { op: "expectRidePrompt", target: "own", frames: 90 },
                    // B's horse, with ours sent away (its call wait) so its GET_ON cannot show.
                    { op: "setHorseHidden", hidden: true },
                    { op: "expectRidePrompt", target: "remote", frames: 60 },
                    ...barrier("done", "B"),
                    { op: "quit" },
                ],
            },
            {
                name: "B",
                start: B_START,
                cvars: colorCvars(RED),
                steps: [
                    ...connect,
                    ...meetIn(field, "A"),
                    { op: "clearEnemies" },
                    { op: "wait", frames: 30 },
                    { op: "spawnHorse", dist: 300, side: 400 },
                    { op: "signal", name: "spawned" },
                    ...barrier("done", "A"),
                    { op: "quit" },
                ],
            },
        ],
    },
    {
        name: "horse-hide",
        description: "B's horse waiting to be called hides its puppet; with hidePlayersInCutscene A's own cutscene and B's hide it too, and it comes back after each",
        timeoutSec: 300,
        cvars: [...COMMON_CVARS, tt("hide_players_in_cutscene", 1)],
        instances: [
            {
                name: "A",
                start: field,
                steps: [
                    ...connect,
                    ...meetIn(field, "B"),
                    { op: "clearEnemies" },
                    { op: "waitRoomState", key: "hidePlayersInCutscene", value: true, timeoutSec: 20 },
                    { op: "waitSignal", name: "spawned", from: "B", timeoutSec: 60 },
                    { op: "expectRemoteHorse", frames: 15 },
                    ...barrier("saw-horse", "B"),
                    ...barrier("call-wait", "B"),
                    { op: "expectNoRemoteHorse" },
                    ...barrier("saw-call-wait", "B"),
                    ...barrier("called", "B"),
                    { op: "expectRemoteHorse", frames: 15 },
                    { op: "forceCutscene", on: true },
                    { op: "expectNoRemoteHorse", timeoutSec: 2 },
                    { op: "forceCutscene", on: null },
                    { op: "expectRemoteHorse", frames: 15 },
                    ...barrier("saw-called", "B"),
                    ...barrier("b-cutscene", "B"),
                    { op: "expectNoRemoteHorse" },
                    ...barrier("saw-b-cutscene", "B"),
                    ...barrier("b-cutscene-end", "B"),
                    { op: "expectRemoteHorse", frames: 15 },
                    ...barrier("done", "B"),
                    { op: "quit" },
                ],
            },
            {
                name: "B",
                start: field,
                steps: [
                    ...connect,
                    ...meetIn(field, "A"),
                    { op: "clearEnemies" },
                    { op: "waitRoomState", key: "hidePlayersInCutscene", value: true, timeoutSec: 20 },
                    { op: "spawnHorse", dist: 300 },
                    { op: "signal", name: "spawned" },
                    ...barrier("saw-horse", "A"),
                    { op: "setHorseHidden", hidden: true },
                    ...barrier("call-wait", "A"),
                    ...barrier("saw-call-wait", "A"),
                    { op: "setHorseHidden", hidden: false },
                    ...barrier("called", "A"),
                    ...barrier("saw-called", "A"),
                    { op: "forceCutscene", on: true },
                    ...barrier("b-cutscene", "A"),
                    ...barrier("saw-b-cutscene", "A"),
                    { op: "forceCutscene", on: null },
                    ...barrier("b-cutscene-end", "A"),
                    ...barrier("done", "A"),
                    { op: "quit" },
                ],
            },
        ],
    },
    {
        name: "horse-park",
        description: "B leaves its horse in Faron Field and goes to South Faron: A, still in the field, sees her parked with her card; B comes back and its stream takes over; A hops away and back and reconnects, and she is there each time",
        timeoutSec: 600,
        cvars: COMMON_CVARS,
        instances: [
            {
                name: "A",
                start: field,
                steps: [
                    ...connect,
                    ...meetIn(field, "B"),
                    { op: "clearEnemies" },
                    { op: "waitSignal", name: "spawned", from: "B", timeoutSec: 60 },
                    { op: "expectRemoteHorse", parked: false, frames: 15 },
                    ...barrier("b-leaves", "B"),
                    { op: "expectRemoteHorse", parked: true, tint: true, frames: 30, timeoutSec: 60 },
                    ...onCamera([{ op: "expectRemoteHorse", parked: true, card: "B's Lilly", onScreen: true, frames: 5 }], "parked"),
                    ...barrier("saw-parked", "B"),
                    { op: "waitSignal", name: "b-back", from: "B", timeoutSec: 120 },
                    { op: "expectRemoteHorse", parked: false, frames: 15, timeoutSec: 60 },
                    // A leaves and comes back: the puppet is made again from B's stream.
                    warp(STAGES.southFaron),
                    waitStage(STAGES.southFaron),
                    { op: "expectNoRemoteHorse" },
                    warp(field),
                    waitStage(field),
                    { op: "clearEnemies" },
                    { op: "expectRemoteHorse", parked: false, frames: 15, timeoutSec: 60 },
                    // A late join: the server's cached state and B's next keyframe bring her back.
                    { op: "disconnect" },
                    { op: "wait", sec: 2 },
                    ...connect,
                    { op: "expectRemoteHorse", parked: false, frames: 15, timeoutSec: 60 },
                    { op: "expectRemoteHorse", card: "B's Lilly", frames: 5 },
                    ...barrier("done", "B"),
                    { op: "quit" },
                ],
            },
            {
                name: "B",
                start: B_START,
                cvars: colorCvars(RED),
                steps: [
                    ...connect,
                    ...meetIn(field, "A"),
                    { op: "clearEnemies" },
                    { op: "spawnHorse", dist: 300 },
                    { op: "wait", frames: 30 },
                    { op: "signal", name: "spawned" },
                    ...barrier("b-leaves", "A"),
                    warp(STAGES.southFaron),
                    waitStage(STAGES.southFaron),
                    ...barrier("saw-parked", "A"),
                    warp(field),
                    waitStage(field),
                    { op: "clearEnemies" },
                    { op: "expectLocalHorse", present: true },
                    { op: "signal", name: "b-back" },
                    ...barrier("done", "A"),
                    { op: "quit" },
                ],
            },
        ],
    },
    {
        name: "horse-trio",
        description: "B and C both show their Epona to A: two puppets at once, each with its own private Horse.arc (heap use logged)",
        timeoutSec: 360,
        cvars: COMMON_CVARS,
        instances: [
            {
                name: "A",
                start: field,
                launchDelayMs: 1500,
                steps: [
                    ...connect,
                    waitStage(field),
                    { op: "waitPeers", count: 2, sameStage: true, timeoutSec: 90 },
                    { op: "waitDummies", count: 2, timeoutSec: 60 },
                    ...barrier("met", "B"),
                    ...barrier("met-c", "C"),
                    { op: "waitSignal", name: "spawned", from: "B", timeoutSec: 60 },
                    { op: "waitSignal", name: "spawned", from: "C", timeoutSec: 60 },
                    { op: "expectRemoteHorse", count: 2, frames: 30 },
                    ...barrier("done", "B"),
                    ...barrier("done-c", "C"),
                    { op: "quit" },
                ],
            },
            {
                name: "B",
                start: field,
                launchDelayMs: 1500,
                steps: [
                    ...connect,
                    waitStage(field),
                    { op: "waitPeers", count: 2, sameStage: true, timeoutSec: 90 },
                    { op: "clearEnemies" },
                    ...barrier("met", "A"),
                    { op: "walk", frames: 40, stickX: 1, stickY: 0 },
                    { op: "spawnHorse", dist: 300 },
                    { op: "signal", name: "spawned" },
                    ...barrier("done", "A"),
                    { op: "quit" },
                ],
            },
            {
                name: "C",
                start: field,
                steps: [
                    ...connect,
                    waitStage(field),
                    { op: "waitPeers", count: 2, sameStage: true, timeoutSec: 90 },
                    { op: "clearEnemies" },
                    ...barrier("met-c", "A"),
                    { op: "walk", frames: 40, stickX: -1, stickY: 0 },
                    { op: "spawnHorse", dist: 300 },
                    { op: "signal", name: "spawned" },
                    ...barrier("done-c", "A"),
                    { op: "quit" },
                ],
            },
        ],
    },
];
