// Remote players' items and projectiles (visual only: with PvP off they fly through).

const { STAGES, ITEMS, EVENTS, COMMON_CVARS, barrier, meetIn, connect } = require("../lib");

const PAD_X = 0x400;
const STICK = 0x40016;  // Z2SE_HIT_AL_ARROW_STICK
const HIT_SWORD = 0x40000;  // Z2SE_HIT_SWORD
const DJGIRI_ALL = 0x9D0 | (5 << 16);  // the great spin's six landing particles in one event
// 75% of the dummy's 0xC00000 solid heap: createHeap warns above it.
const HEAP_LIMIT = 0x900000;
const CVARS = [...COMMON_CVARS, "game.damageMultiplier=1", "game.instantDeath=false",
               "game.infiniteHearts=false"];
const room = (name, value) => [
    { op: "setRoomOption", name, value },
    { op: "waitRoomOption", name, value, timeoutSec: 20 },
];
// More than a knockdown and its i-frames.
const recover = { op: "wait", frames: 100 };
// The bow on X: held through the ready animation, released to shoot.
const bowShot = [
    { op: "walk", frames: 25, stickX: 0, stickY: 0, buttons: PAD_X },
    { op: "wait", frames: 30 },
];

module.exports = [
    {
        name: "itemfx-inject",
        description: "B's updates carry a stuck arrow, a bomb, a flying boomerang and one of each event; A's dummy draws them, plays each event once, and clears them when they stop",
        timeoutSec: 300,
        cvars: COMMON_CVARS,
        instances: [
            {
                name: "A",
                start: STAGES.southFaron,
                steps: [
                    ...connect,
                    ...meetIn(STAGES.southFaron, "B"),
                    { op: "markRemoteItemFx" },
                    { op: "expectRemoteItemFx", maxDrawn: { arrow: 0, boomerang: 0, bomb: 0 }, maxHeapUsed: HEAP_LIMIT },
                    ...barrier("marked", "B"),
                    // The explosion's light lasts about half a second.
                    { op: "expectRemoteItemFx", explosions: 1, minLights: 1, timeoutSec: 10 },
                    {
                        op: "expectRemoteItemFx",
                        minDrawn: { arrow: 1, boomerang: 1, bomb: 1 },
                        tornado: true,
                        // The bomb's fuse (2) and the boomerang's trails (3).
                        minEmitters: 5,
                        frames: 20,
                        timeoutSec: 10,
                    },
                    { op: "log", msg: "ITEMFX_HOLD injected" },
                    { op: "expectRemoteItemFx", hitMarks: 1, sounds: 1, splashes: 1 },
                    // Played once each, although B's slots stay for many packets.
                    { op: "wait", frames: 60 },
                    { op: "expectRemoteItemFx", minSeen: { arrow: 1, boomerang: 1, bomb: 1 }, maxExplosions: 1 },
                    { op: "expectRemoteItemFx", maxDrawn: { arrow: 0, boomerang: 0, bomb: 0 }, tornado: false, maxLights: 0, frames: 30, timeoutSec: 20 },
                    ...barrier("cleared", "B"),
                    { op: "quit" },
                ],
            },
            {
                name: "B",
                start: STAGES.southFaron,
                steps: [
                    ...connect,
                    ...meetIn(STAGES.southFaron, "A"),
                    ...barrier("marked", "A"),
                    {
                        op: "injectItemFx",
                        packets: 150,
                        slots: [
                            { kind: "arrow", sub: 0, state: 2, forward: 120, up: 60 },
                            { kind: "bomb", sub: 0, state: 2, forward: 160, fuse: 400 },
                            { kind: "boomerang", state: 1, forward: 220, up: 100, aux: 256 },
                        ],
                        events: [
                            { type: "sound", arg: STICK, forward: 120, up: 60 },
                            { type: "hitMark", arg: 9, forward: 120, up: 60 },
                            { type: "explode", arg: 0, forward: 300 },
                            { type: "water", arg: 16, forward: 250 },
                        ],
                    },
                    { op: "expectLocalItemFx", events: { explode: 1, hitMark: 1, sound: 1, water: 1 } },
                    ...barrier("cleared", "A"),
                    { op: "quit" },
                ],
            },
        ],
    },
    {
        name: "itemfx-shots",
        description: "B shoots three slingshot seeds, two arrows and a bomb arrow at the ground; A's dummy draws them in flight, the seeds' bursts, the arrows stuck and the bomb arrow's explosion",
        timeoutSec: 300,
        cvars: COMMON_CVARS,
        instances: [
            {
                name: "A",
                start: STAGES.southFaron,
                steps: [
                    ...connect,
                    ...meetIn(STAGES.southFaron, "B"),
                    { op: "markRemoteItemFx" },
                    ...barrier("marked", "B"),
                    { op: "expectRemoteItemFx", minSeen: { arrow: 3 }, hitMarks: 1, timeoutSec: 20 },
                    ...barrier("seeds-seen", "B"),
                    { op: "expectRemoteItemFx", minSeen: { arrow: 5 }, sounds: 1, minDrawn: { arrow: 1 }, timeoutSec: 20 },
                    { op: "log", msg: "ITEMFX_HOLD arrows" },
                    ...barrier("arrows-seen", "B"),
                    { op: "expectRemoteItemFx", minSeen: { arrow: 6 }, explosions: 1, minLights: 1, timeoutSec: 20 },
                    { op: "expectRemoteItemFx", maxHeapUsed: HEAP_LIMIT },
                    ...barrier("done", "B"),
                    { op: "quit" },
                ],
            },
            {
                name: "B",
                start: STAGES.southFaron,
                steps: [
                    ...connect,
                    ...meetIn(STAGES.southFaron, "A"),
                    ...barrier("marked", "A"),
                    { op: "spawnLocalItem", kind: "seed", count: 3, pitch: 12 },
                    { op: "expectLocalItemFx", objects: { arrow: 3 }, events: { hitMark: 1 }, timeoutSec: 15 },
                    ...barrier("seeds-seen", "A"),
                    { op: "spawnLocalItem", kind: "arrow", count: 2, pitch: 15 },
                    { op: "expectLocalItemFx", objects: { arrow: 5 }, events: { sound: 1 }, timeoutSec: 15 },
                    ...barrier("arrows-seen", "A"),
                    { op: "spawnLocalItem", kind: "bombArrow", pitch: 15 },
                    { op: "log", msg: "ITEMFX_HOLD bomb arrow" },
                    { op: "expectLocalItemFx", objects: { arrow: 6 }, events: { explode: 1 }, timeoutSec: 15 },
                    ...barrier("done", "A"),
                    { op: "quit" },
                ],
            },
        ],
    },
    {
        name: "itemfx-boomerang",
        description: "B throws the boomerang twice, then aims it; A's dummy draws the boomerang with its tornado in flight and the glow in hand while aiming",
        timeoutSec: 300,
        cvars: COMMON_CVARS,
        instances: [
            {
                name: "A",
                start: STAGES.southFaron,
                steps: [
                    ...connect,
                    ...meetIn(STAGES.southFaron, "B"),
                    { op: "markRemoteItemFx" },
                    ...barrier("throwing", "B"),
                    // The tornado, and its trails (KISEKI_A/B, LEAF_A).
                    { op: "expectRemoteItemFx", minDrawn: { boomerang: 1 }, tornado: true, minEmitters: 3, timeoutSec: 20 },
                    { op: "log", msg: "ITEMFX_HOLD boomerang" },
                    { op: "expectRemoteItemFx", minSeen: { boomerang: 2 }, timeoutSec: 20 },
                    { op: "expectRemoteItemFx", maxDrawn: { boomerang: 0 }, tornado: false, timeoutSec: 20 },
                    ...barrier("thrown", "B"),
                    { op: "waitSignal", name: "aiming", from: "B", timeoutSec: 60 },
                    { op: "expectRemoteItemFx", boomCharge: true, timeoutSec: 5 },
                    { op: "expectRemoteItemFx", boomCharge: false, timeoutSec: 20 },
                    ...barrier("aimed", "B"),
                    { op: "quit" },
                ],
            },
            {
                name: "B",
                start: STAGES.southFaron,
                steps: [
                    ...connect,
                    ...meetIn(STAGES.southFaron, "A"),
                    { op: "giveItem", item: ITEMS.boomerang },
                    { op: "assignItemX", item: ITEMS.boomerang },
                    ...barrier("throwing", "A"),
                    ...[1, 2].flatMap(() => [
                        { op: "walk", frames: 8, stickX: 0, stickY: 0, buttons: PAD_X },
                        { op: "wait", frames: 90 },
                    ]),
                    { op: "expectLocalItemFx", objects: { boomerang: 2 } },
                    ...barrier("thrown", "A"),
                    // Held past the quick-throw window: the aim (procBoomerangSubject).
                    { op: "walk", frames: 75, stickX: 0, stickY: 0, buttons: PAD_X, async: true },
                    { op: "wait", frames: 30 },
                    { op: "signal", name: "aiming" },
                    { op: "wait", frames: 150 },
                    ...barrier("aimed", "A"),
                    { op: "quit" },
                ],
            },
        ],
    },
    {
        name: "itemfx-bombs",
        description: "B sets a bomb down on A's dummy, a water bomb and a bombling; A's dummy draws them with their fuses and plays the explosions, and A loses no life (PvP off)",
        timeoutSec: 360,
        cvars: CVARS,
        instances: [
            {
                name: "A",
                start: STAGES.southFaron,
                steps: [
                    ...connect,
                    ...meetIn(STAGES.southFaron, "B"),
                    { op: "setLife", value: 12 },
                    { op: "wait", frames: 10 },
                    { op: "markLife" },
                    { op: "markRemoteItemFx" },
                    ...barrier("marked", "B"),
                    { op: "expectRemoteItemFx", minSeen: { bomb: 3 }, minDrawn: { bomb: 2 }, timeoutSec: 20 },
                    { op: "log", msg: "ITEMFX_HOLD bombs" },
                    { op: "expectRemoteItemFx", explosions: 1, minLights: 1, timeoutSec: 20 },
                    { op: "log", msg: "ITEMFX_HOLD explosion" },
                    { op: "expectRemoteItemFx", explosions: 3, timeoutSec: 30 },
                    { op: "expectRemoteItemFx", maxDrawn: { bomb: 0 }, maxLights: 0, frames: 30, timeoutSec: 20 },
                    { op: "expectLifeDelta", delta: 0, frames: 30 },
                    ...barrier("done", "B"),
                    { op: "quit" },
                ],
            },
            {
                name: "B",
                start: STAGES.southFaron,
                steps: [
                    ...connect,
                    ...meetIn(STAGES.southFaron, "A"),
                    ...barrier("marked", "A"),
                    { op: "spawnLocalItem", kind: "bomb", atDummy: true },
                    // Out of each other's blast (225); a bombling over a drop blows up at once.
                    { op: "spawnLocalItem", kind: "waterBomb", forward: -250 },
                    { op: "spawnLocalItem", kind: "bombling", forward: 40, up: 20 },
                    { op: "expectLocalItemFx", objects: { bomb: 3 }, events: { explode: 3 }, timeoutSec: 30 },
                    ...barrier("done", "A"),
                    { op: "quit" },
                ],
            },
        ],
    },
    {
        name: "itemfx-hidden",
        description: "A's cutscene hides B's burning bomb and its explosion; afterwards the explosion is not replayed",
        timeoutSec: 300,
        cvars: COMMON_CVARS,
        instances: [
            {
                name: "A",
                start: STAGES.southFaron,
                steps: [
                    ...connect,
                    ...meetIn(STAGES.southFaron, "B"),
                    ...room("hidePlayersInCutscene", true),
                    { op: "markRemoteItemFx" },
                    { op: "forceCutscene", on: true },
                    { op: "wait", frames: 5 },
                    ...barrier("hidden", "B"),
                    // Longer than the bomb's 160-tick fuse and its flash.
                    { op: "expectRemoteItemFx", maxDrawn: { bomb: 0 }, maxLights: 0, maxExplosions: 0, frames: 240 },
                    { op: "forceCutscene", on: null },
                    { op: "wait", frames: 30 },
                    { op: "expectRemoteItemFx", maxExplosions: 0, maxDrawn: { bomb: 0 }, maxLights: 0, frames: 30 },
                    ...barrier("done", "B"),
                    { op: "quit" },
                ],
            },
            {
                name: "B",
                start: STAGES.southFaron,
                steps: [
                    ...connect,
                    ...meetIn(STAGES.southFaron, "A"),
                    ...room("hidePlayersInCutscene", true),
                    ...barrier("hidden", "A"),
                    { op: "spawnLocalItem", kind: "bomb", forward: 200 },
                    { op: "expectLocalItemFx", events: { explode: 1 }, timeoutSec: 15 },
                    ...barrier("done", "A"),
                    { op: "quit" },
                ],
            },
        ],
    },
    {
        name: "pvp-bomb",
        description: "PvP projectiles: with PvP off A's arrow flies through B's dummy; with it on a bomb arrow's blast and a bomb knock B down (3), an arrow takes 2, a seed and the boomerang stagger",
        timeoutSec: 480,
        cvars: CVARS,
        instances: [
            {
                name: "A",
                start: STAGES.southFaron,
                steps: [
                    ...connect,
                    ...meetIn(STAGES.southFaron, "B"),
                    { op: "giveItem", item: ITEMS.bow },
                    { op: "assignItemX", item: ITEMS.bow },
                    ...barrier("b-marked-off", "B"),
                    { op: "approachDummy", dist: 300 },
                    ...bowShot,
                    { op: "wait", frames: 30 },
                    { op: "expectPvpStats", target: "B", sent: 0 },
                    ...barrier("off-shot", "B"),
                    ...room("pvpMode", true),
                    ...barrier("b-marked-on", "B"),
                    { op: "expectDummyHurtbox", registered: true, timeoutSec: 10 },
                    { op: "approachDummy", dist: 300 },
                    { op: "explodeAtDummy" },
                    { op: "expectPvpStats", target: "B", sent: 1, applied: 1, damage: 3, timeoutSec: 10 },
                    ...barrier("blast-checked", "B"),
                    { op: "expectDummyHurtbox", registered: true, timeoutSec: 20 },
                    { op: "approachDummy", dist: 300 },
                    { op: "spawnLocalItem", kind: "bomb", atDummy: true },
                    // The bomb's 160-tick fuse.
                    { op: "expectPvpStats", target: "B", applied: 2, damage: 6, timeoutSec: 15 },
                    ...barrier("bomb-checked", "B"),
                    { op: "expectDummyHurtbox", registered: true, timeoutSec: 20 },
                    { op: "approachDummy", dist: 300 },
                    // The real bow: ready and release, straight at the dummy we face.
                    ...bowShot,
                    { op: "expectPvpStats", target: "B", applied: 3, damage: 8, timeoutSec: 10 },
                    ...barrier("arrow-checked", "B"),
                    { op: "expectDummyHurtbox", registered: true, timeoutSec: 20 },
                    { op: "approachDummy", dist: 300 },
                    { op: "spawnLocalItem", kind: "seed", aimAtDummy: true },
                    { op: "expectPvpStats", target: "B", applied: 4, damage: 8, timeoutSec: 10 },
                    ...barrier("seed-checked", "B"),
                    // A quick throw flies straight out: its wind sweeps the dummy.
                    { op: "giveItem", item: ITEMS.boomerang },
                    { op: "assignItemX", item: ITEMS.boomerang },
                    // The X button takes the new item over on a later frame.
                    { op: "wait", frames: 30 },
                    { op: "expectDummyHurtbox", registered: true, timeoutSec: 20 },
                    { op: "approachDummy", dist: 300 },
                    { op: "walk", frames: 8, stickX: 0, stickY: 0, buttons: PAD_X },
                    { op: "expectPvpStats", target: "B", applied: 5, damage: 8, timeoutSec: 10 },
                    ...barrier("boomerang-checked", "B"),
                    { op: "quit" },
                ],
            },
            {
                name: "B",
                start: STAGES.southFaron,
                steps: [
                    ...connect,
                    ...meetIn(STAGES.southFaron, "A"),
                    // The full three hearts of a new save: more would be clamped to them.
                    { op: "setLife", value: 12 },
                    { op: "wait", frames: 10 },
                    { op: "markLife" },
                    ...barrier("b-marked-off", "A"),
                    ...barrier("off-shot", "A"),
                    { op: "expectLifeDelta", delta: 0, frames: 1 },
                    { op: "expectPvpTaken", count: 0 },
                    ...room("pvpMode", true),
                    { op: "markLife" },
                    ...barrier("b-marked-on", "A"),
                    { op: "expectReaction", knockback: "knockdown" },
                    { op: "expectLifeDelta", delta: -3, timeoutSec: 10 },
                    { op: "expectPvpTaken", count: 1, damage: 3 },
                    recover,
                    { op: "expectReaction", knockback: "none", timeoutSec: 20 },
                    ...barrier("blast-checked", "A"),
                    { op: "expectReaction", knockback: "knockdown", timeoutSec: 20 },
                    { op: "expectLifeDelta", delta: -6, timeoutSec: 10 },
                    recover,
                    { op: "expectReaction", knockback: "none", timeoutSec: 20 },
                    ...barrier("bomb-checked", "A"),
                    { op: "expectLifeDelta", delta: -8, timeoutSec: 20 },
                    recover,
                    { op: "expectReaction", knockback: "none", timeoutSec: 20 },
                    ...barrier("arrow-checked", "A"),
                    { op: "expectReaction", knockback: "light", timeoutSec: 20 },
                    { op: "expectPvpTaken", count: 4, damage: 8, timeoutSec: 10 },
                    { op: "expectReaction", knockback: "none", timeoutSec: 20 },
                    ...barrier("seed-checked", "A"),
                    { op: "expectReaction", knockback: "light", timeoutSec: 30 },
                    { op: "expectPvpTaken", count: 5, damage: 8, timeoutSec: 10 },
                    { op: "expectLifeDelta", delta: -8, frames: 1 },
                    ...barrier("boomerang-checked", "A"),
                    { op: "quit" },
                ],
            },
        ],
    },
    {
        name: "itemfx-clawshot",
        description: "At the Forest Temple entrance B's updates carry a clawshot tip out; then B fires its real clawshot: A's dummy draws the chain out to the tip and back, with the chain's level sounds",
        timeoutSec: 300,
        cvars: COMMON_CVARS,
        instances: [
            {
                name: "A",
                start: STAGES.forestTemple,
                steps: [
                    ...connect,
                    ...meetIn(STAGES.forestTemple, "B"),
                    { op: "markRemoteItemFx" },
                    ...barrier("marked", "B"),
                    // While B aims, its updates carry a tip 500 units ahead of it: the chain is drawn.
                    { op: "expectRemoteItemFx", hookChain: true, minTipDist: 250, frames: 10, timeoutSec: 20 },
                    { op: "expectRemoteItemFx", hookChain: false, timeoutSec: 20 },
                    // B's real shot is out for ~6 ticks: counted by the dummy, as playout may skip a tick.
                    { op: "markRemoteItemFx" },
                    { op: "expectRemoteItemFx", minHookShots: 1, minHookPeak: 150, timeoutSec: 20 },
                    { op: "log", msg: "ITEMFX_HOLD clawshot" },
                    { op: "expectRemoteItemFx", levelSfx: true, timeoutSec: 20 },
                    { op: "expectRemoteItemFx", hookChain: false, timeoutSec: 20 },
                    ...barrier("fired", "B"),
                    { op: "quit" },
                ],
            },
            {
                name: "B",
                start: STAGES.forestTemple,
                steps: [
                    ...connect,
                    ...meetIn(STAGES.forestTemple, "A"),
                    { op: "giveItem", item: ITEMS.hookshot },
                    { op: "assignItemX", item: ITEMS.hookshot },
                    // Facing A 300 units off: the tip flies through the dummy, not into a wall.
                    { op: "approachDummy", dist: 300 },
                    { op: "wait", frames: 30 },
                    ...barrier("marked", "A"),
                    // Held through the aim, released to fire (checkUpperItemActionHookshot).
                    { op: "walk", frames: 150, stickX: 0, stickY: 0, buttons: PAD_X, async: true },
                    { op: "wait", frames: 20 },
                    { op: "injectItemFx", packets: 40, hook: { mode: 3, forward: 500, up: 100 } },
                    { op: "wait", frames: 250 },
                    { op: "expectLocalItemFx", hookOutTicks: 5, minHookDist: 200, levelSfxTicks: 1 },
                    ...barrier("fired", "A"),
                    { op: "quit" },
                ],
            },
        ],
    },
    {
        name: "itemfx-ironball",
        description: "B takes out the ball and chain, swings and throws it: A's dummy holds the ball, draws it out on its chain and plays its landing's impact",
        timeoutSec: 300,
        cvars: COMMON_CVARS,
        instances: [
            {
                name: "A",
                start: STAGES.southFaron,
                steps: [
                    ...connect,
                    ...meetIn(STAGES.southFaron, "B"),
                    { op: "markRemoteItemFx" },
                    ...barrier("marked", "B"),
                    { op: "expectDummyLook", heldItem: ITEMS.ironball, timeoutSec: 20 },
                    ...barrier("held", "B"),
                    // Thrown (modes 3-6) and out on its chain.
                    { op: "expectRemoteItemFx", minIronBallMode: 3, minIronBallDist: 80, timeoutSec: 20 },
                    { op: "log", msg: "ITEMFX_HOLD ball and chain" },
                    // Its landing's clang (setIronBallPos's Z2SE_HIT_HAMMER), then back in hand.
                    { op: "expectRemoteItemFx", sounds: 1, timeoutSec: 20 },
                    { op: "expectRemoteItemFx", maxIronBallMode: 0, timeoutSec: 30 },
                    { op: "expectRemoteItemFx", maxHeapUsed: HEAP_LIMIT },
                    ...barrier("thrown", "B"),
                    { op: "quit" },
                ],
            },
            {
                name: "B",
                start: STAGES.southFaron,
                steps: [
                    ...connect,
                    ...meetIn(STAGES.southFaron, "A"),
                    { op: "giveItem", item: ITEMS.ironball },
                    { op: "assignItemX", item: ITEMS.ironball },
                    { op: "wait", frames: 30 },
                    ...barrier("marked", "A"),
                    // Out of the pouch (a tap: held on, it would swing).
                    { op: "walk", frames: 2, stickX: 0, stickY: 0, buttons: PAD_X },
                    { op: "wait", frames: 60 },
                    ...barrier("held", "A"),
                    // Held to swing, released to throw.
                    { op: "walk", frames: 60, stickX: 0, stickY: 0, buttons: PAD_X },
                    { op: "wait", frames: 150 },
                    { op: "expectLocalItemFx", ironBallTicks: 10, events: { sound: 1 } },
                    ...barrier("thrown", "A"),
                    { op: "quit" },
                ],
            },
        ],
    },
    {
        name: "itemfx-spinner-rod",
        description: "B rides the spinner, then throws the powered Dominion Rod's ball: A's dummy draws the spinner with its ride sound, then the glowing ball with its light",
        timeoutSec: 300,
        cvars: COMMON_CVARS,
        instances: [
            {
                name: "A",
                start: STAGES.southFaron,
                steps: [
                    ...connect,
                    ...meetIn(STAGES.southFaron, "B"),
                    { op: "markRemoteItemFx" },
                    ...barrier("marked", "B"),
                    { op: "expectRemoteItemFx", minDrawn: { spinner: 1 }, levelSfx: true, timeoutSec: 30 },
                    { op: "log", msg: "ITEMFX_HOLD spinner" },
                    ...barrier("spun", "B"),
                    { op: "expectRemoteItemFx", maxDrawn: { spinner: 0 }, timeoutSec: 30 },
                    ...barrier("rod", "B"),
                    // The ball on the rod glows (and lights) once the rod holds the power.
                    { op: "expectRemoteItemFx", minDrawn: { crodBall: 1 }, minLights: 1, timeoutSec: 30 },
                    { op: "log", msg: "ITEMFX_HOLD rod ball" },
                    { op: "expectRemoteItemFx", minSeen: { spinner: 1, crodBall: 1 } },
                    ...barrier("rod-done", "B"),
                    { op: "expectRemoteItemFx", maxLights: 0, timeoutSec: 30 },
                    { op: "quit" },
                ],
            },
            {
                name: "B",
                start: STAGES.southFaron,
                steps: [
                    ...connect,
                    ...meetIn(STAGES.southFaron, "A"),
                    { op: "giveItem", item: ITEMS.spinner },
                    { op: "giveItem", item: ITEMS.copyRod },
                    { op: "assignItemX", item: ITEMS.spinner },
                    { op: "wait", frames: 30 },
                    ...barrier("marked", "A"),
                    { op: "walk", frames: 8, stickX: 0, stickY: 0, buttons: PAD_X },
                    { op: "walk", frames: 90, stickX: 0, stickY: 1 },
                    { op: "expectLocalItemFx", objects: { spinner: 1 }, levelSfxTicks: 1 },
                    ...barrier("spun", "A"),
                    // Off the spinner (it goes when the rider jumps off).
                    { op: "walk", frames: 8, stickX: 0, stickY: 0, buttons: PAD_X },
                    { op: "wait", frames: 90 },
                    { op: "setEventBit", no: EVENTS.copyRodPower },
                    { op: "assignItemX", item: ITEMS.copyRod },
                    { op: "wait", frames: 30 },
                    ...barrier("rod", "A"),
                    // Out, then held to aim and released to throw the ball.
                    { op: "walk", frames: 8, stickX: 0, stickY: 0, buttons: PAD_X },
                    { op: "wait", frames: 60 },
                    { op: "walk", frames: 25, stickX: 0, stickY: 0, buttons: PAD_X },
                    { op: "wait", frames: 120 },
                    { op: "expectLocalItemFx", objects: { crodBall: 1 } },
                    ...barrier("rod-done", "A"),
                    // Put away: no ball and no light left behind.
                    { op: "walk", frames: 8, stickX: 0, stickY: 0, buttons: 0x200 },
                    { op: "wait", frames: 60 },
                    { op: "quit" },
                ],
            },
        ],
    },
    {
        name: "itemfx-lantern",
        description: "B's lantern burns with oil and goes out without; B holds the horse call; B's updates carry a great spin landing and a sword clang: A's dummy shows the flame and glow, the horse call and the impacts",
        timeoutSec: 300,
        cvars: COMMON_CVARS,
        instances: [
            {
                name: "A",
                start: STAGES.southFaron,
                steps: [
                    ...connect,
                    ...meetIn(STAGES.southFaron, "B"),
                    { op: "markRemoteItemFx" },
                    ...barrier("marked", "B"),
                    { op: "expectRemoteItemFx", lanternFlame: true, minLanternGlow: 0.9, frames: 10, timeoutSec: 30 },
                    { op: "log", msg: "ITEMFX_HOLD lantern" },
                    ...barrier("lit", "B"),
                    { op: "expectRemoteItemFx", lanternFlame: false, maxLanternGlow: 0.2, timeoutSec: 30 },
                    ...barrier("out", "B"),
                    { op: "expectDummyLook", heldItem: ITEMS.horseFlute, timeoutSec: 30 },
                    ...barrier("called", "B"),
                    { op: "expectRemoteItemFx", particles: 1, sounds: 1, timeoutSec: 20 },
                    ...barrier("impacts", "B"),
                    { op: "quit" },
                ],
            },
            {
                name: "B",
                start: STAGES.southFaron,
                steps: [
                    ...connect,
                    ...meetIn(STAGES.southFaron, "A"),
                    { op: "giveItem", item: ITEMS.lantern },
                    { op: "giveItem", item: ITEMS.horseFlute },
                    { op: "setOil" },
                    { op: "assignItemX", item: ITEMS.lantern },
                    { op: "wait", frames: 30 },
                    ...barrier("marked", "A"),
                    { op: "walk", frames: 8, stickX: 0, stickY: 0, buttons: PAD_X },
                    { op: "wait", frames: 30 },
                    ...barrier("lit", "A"),
                    { op: "setOil", value: 0 },
                    { op: "wait", frames: 30 },
                    ...barrier("out", "A"),
                    { op: "assignItemX", item: ITEMS.horseFlute },
                    { op: "wait", frames: 30 },
                    { op: "walk", frames: 8, stickX: 0, stickY: 0, buttons: PAD_X },
                    { op: "wait", frames: 30 },
                    ...barrier("called", "A"),
                    {
                        op: "injectItemFx",
                        packets: 5,
                        events: [
                            { type: "particle", arg: DJGIRI_ALL, forward: 100 },
                            { type: "sound", arg: HIT_SWORD, forward: 100, up: 50 },
                        ],
                    },
                    { op: "expectLocalItemFx", events: { particle: 1, sound: 1 } },
                    ...barrier("impacts", "A"),
                    { op: "quit" },
                ],
            },
        ],
    },
    {
        // Window captures (A logs ITEMFX_LOOK <what>): B throws and shoots toward A.
        name: "itemfx-look",
        description: "B throws, shoots and blasts toward A for window captures (no checks)",
        timeoutSec: 360,
        cvars: COMMON_CVARS,
        instances: [
            {
                name: "A",
                start: STAGES.forestTemple,
                steps: [
                    ...connect,
                    ...meetIn(STAGES.forestTemple, "B"),
                    ...barrier("placed", "B"),
                    { op: "viewDummy", back: 260, side: 90, up: 160 },
                    ...barrier("a-ready", "B"),
                    ...["boomerang", "arrows", "seeds", "bomb arrow"].flatMap((what) => [
                        { op: "waitSignal", name: what, from: "B", timeoutSec: 60 },
                        { op: "log", msg: `ITEMFX_LOOK ${what}` },
                    ]),
                    ...barrier("look-done", "B"),
                    { op: "quit" },
                ],
            },
            {
                name: "B",
                start: STAGES.forestTemple,
                steps: [
                    ...connect,
                    ...meetIn(STAGES.forestTemple, "A"),
                    { op: "giveItem", item: ITEMS.boomerang },
                    { op: "giveItem", item: ITEMS.bow },
                    { op: "approachDummy", dist: 220 },
                    ...barrier("placed", "A"),
                    ...barrier("a-ready", "A"),
                    { op: "assignItemX", item: ITEMS.boomerang },
                    { op: "signal", name: "boomerang" },
                    ...[1, 2].flatMap(() => [
                        { op: "walk", frames: 8, stickX: 0, stickY: 0, buttons: PAD_X },
                        { op: "wait", frames: 80 },
                    ]),
                    { op: "assignItemX", item: ITEMS.bow },
                    { op: "signal", name: "arrows" },
                    ...bowShot, ...bowShot, ...bowShot,
                    { op: "signal", name: "seeds" },
                    { op: "spawnLocalItem", kind: "seed", count: 3, aimAtDummy: true },
                    { op: "wait", frames: 60 },
                    { op: "signal", name: "bomb arrow" },
                    { op: "spawnLocalItem", kind: "bombArrow", aimAtDummy: true },
                    { op: "wait", frames: 120 },
                    ...barrier("look-done", "A"),
                    { op: "quit" },
                ],
            },
        ],
    },
    {
        // Window captures of daAlink's own items, like itemfx-look, with B 250 units in front of A.
        name: "itemfx-look-held",
        description: "B fires the clawshot, throws the ball, rides the spinner and swings the lantern toward A for window captures (no checks)",
        timeoutSec: 360,
        cvars: COMMON_CVARS,
        instances: [
            {
                name: "A",
                start: STAGES.forestTemple,
                steps: [
                    ...connect,
                    ...meetIn(STAGES.forestTemple, "B"),
                    ...barrier("placed", "B"),
                    { op: "viewDummy", back: 260, side: 90, up: 160 },
                    ...barrier("a-ready", "B"),
                    ...["clawshot", "ball", "spinner"].flatMap((what) => [
                        { op: "waitSignal", name: what, from: "B", timeoutSec: 60 },
                        { op: "log", msg: `ITEMFX_LOOK ${what}` },
                    ]),
                    // From the side: B came back to stand right in front of A.
                    { op: "waitSignal", name: "lantern", from: "B", timeoutSec: 60 },
                    { op: "viewDummy", back: 60, side: 260, up: 90 },
                    { op: "log", msg: "ITEMFX_LOOK lantern" },
                    ...barrier("look-done", "B"),
                    { op: "quit" },
                ],
            },
            {
                name: "B",
                start: STAGES.forestTemple,
                steps: [
                    ...connect,
                    ...meetIn(STAGES.forestTemple, "A"),
                    ...[ITEMS.hookshot, ITEMS.ironball, ITEMS.spinner, ITEMS.lantern].map((item) => ({ op: "giveItem", item })),
                    { op: "setOil" },
                    { op: "approachDummy", dist: 250 },
                    ...barrier("placed", "A"),
                    ...barrier("a-ready", "A"),
                    { op: "assignItemX", item: ITEMS.hookshot },
                    { op: "wait", frames: 30 },
                    { op: "walk", frames: 25, stickX: 0, stickY: 0, buttons: PAD_X },
                    { op: "signal", name: "clawshot" },
                    { op: "wait", frames: 90 },
                    { op: "assignItemX", item: ITEMS.ironball },
                    { op: "wait", frames: 30 },
                    { op: "walk", frames: 2, stickX: 0, stickY: 0, buttons: PAD_X },
                    { op: "wait", frames: 20 },
                    { op: "signal", name: "ball" },
                    { op: "wait", frames: 120 },
                    { op: "assignItemX", item: ITEMS.spinner },
                    { op: "wait", frames: 30 },
                    { op: "walk", frames: 8, stickX: 0, stickY: 0, buttons: PAD_X },
                    { op: "wait", frames: 20 },
                    { op: "signal", name: "spinner" },
                    { op: "wait", frames: 60 },
                    { op: "walk", frames: 8, stickX: 0, stickY: 0, buttons: PAD_X },
                    { op: "wait", frames: 60 },
                    // The spinner took B away.
                    { op: "approachDummy", dist: 200 },
                    { op: "assignItemX", item: ITEMS.lantern },
                    { op: "wait", frames: 30 },
                    { op: "walk", frames: 8, stickX: 0, stickY: 0, buttons: PAD_X },
                    { op: "wait", frames: 20 },
                    { op: "signal", name: "lantern" },
                    { op: "wait", frames: 150 },
                    ...barrier("look-done", "A"),
                    { op: "quit" },
                ],
            },
        ],
    },
    {
        name: "itemfx-fishing",
        description: "B takes out its fishing rod and casts (button fishing): A's dummy of B holds the rod, then shows the bobber out on its line, drawn from B's rod state",
        timeoutSec: 300,
        cvars: [...COMMON_CVARS, "game.buttonFishing=true"],
        instances: [
            {
                name: "A",
                start: STAGES.southFaron,
                steps: [
                    ...connect,
                    ...meetIn(STAGES.southFaron, "B"),
                    { op: "expectRemoteFishing", shown: false },
                    // The camera behind us and off to the side, on B: captures see the rod and line.
                    { op: "horseCamera", target: "dummy", back: 350, up: 220, side: 300, height: 90, hold: true },
                    ...barrier("no-rod", "B"),
                    { op: "waitSignal", name: "rod", from: "B", timeoutSec: 30 },
                    { op: "expectRemoteFishing", action: 0, minLine: 5, timeoutSec: 15 },
                    { op: "mark", msg: "ITEMFX_HOLD rod" },
                    { op: "wait", frames: 60 },
                    ...barrier("saw-rod", "B"),
                    // Cast onto dry land, the line comes back after 20 ticks: counted, not polled.
                    { op: "waitSignal", name: "cast", from: "B", timeoutSec: 30 },
                    { op: "expectRemoteFishing", minCastTicks: 10, timeoutSec: 15 },
                    { op: "horseCamera", release: true },
                    ...barrier("saw-cast", "B"),
                    { op: "quit" },
                ],
            },
            {
                name: "B",
                start: STAGES.southFaron,
                steps: [
                    ...connect,
                    ...meetIn(STAGES.southFaron, "A"),
                    ...barrier("no-rod", "A"),
                    { op: "giveItem", item: ITEMS.fishingRod },
                    { op: "assignItemX", item: ITEMS.fishingRod },
                    { op: "walk", frames: 1, stickX: 0, stickY: 0, buttons: PAD_X },
                    { op: "wait", frames: 40 },
                    { op: "signal", name: "rod" },
                    ...barrier("saw-rod", "A"),
                    // X held seven ticks with button fishing is uki_ready's cast.
                    { op: "mark", msg: "ITEMFX_HOLD cast" },
                    { op: "walk", frames: 9, stickX: 0, stickY: 0, buttons: PAD_X },
                    { op: "wait", frames: 20 },
                    { op: "signal", name: "cast" },
                    ...barrier("saw-cast", "A"),
                    { op: "quit" },
                ],
            },
        ],
    },
];
